name: Build Tweak
on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - uses: theos-org/build-action@v2
        with:
          scheme: roothide
          sdk: 17.0
          
      - uses: actions/upload-artifact@v4
        with:
          name: com.user.autoonlinewallpaper
          path: packages/*.deb
