name: Build Tweak

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: recursive

      # Setup RootHide Theos & SDKs
      - name: Setup RootHide Theos & SDKs
        shell: bash
        run: |
          set -e

          git clone --recursive https://github.com/roothide/theos.git "$HOME/theos"
          git clone https://github.com/DavidDev42/sdks.git "$HOME/theos/sdks"

      # Build RootHide deb package
      - name: Build RootHide deb package
        shell: bash
        run: |
          set -e

          export THEOS="$HOME/theos"

          echo "THEOS=$THEOS"
          echo "macOS: $(sw_vers -productVersion)"
          echo "Architecture: $(uname -m)"
          echo "Theos: $THEOS"

          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      # Upload deb artifact
      - name: Upload deb artifact
        uses: actions/upload-artifact@v7
        with:
          name: AutoOnlineWallpaper-iOS17-RootHide
          path: packages/*.deb
          if-no-files-found: error
