name: Build Tweak

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup RootHide Theos & SDKs
        run: |
          # 1. 强制将 Git 子模块的 SSH 链接重定向为 HTTPS 协议，防止 exit 128 报错
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          
          # 2. 浅克隆 RootHide Theos 及其子模块
          git clone --depth=1 --recursive https://github.com/roothide/theos.git $HOME/theos
          
          # 3. 浅克隆 SDK（只拉取最新提交，加速编译）
          git clone --depth=1 https://github.com/DavidDev42/sdks.git $HOME/theos/sdks

      - name: Build RootHide deb package
        run: |
          export THEOS=$HOME/theos
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoOnlineWallpaper-iOS17-RootHide
          path: packages/*.deb
          if-no-files-found: error
